# Generated by Django 3.0 on 2020-02-03 10:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20200108_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attachments',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='due date'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='due description'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None, verbose_name='tags'),
        ),
    ]
