# Generated by Django 3.0 on 2020-02-17 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='project',
        ),
        migrations.AddField(
            model_name='attachment',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='size',
            field=models.PositiveIntegerField(blank=True, verbose_name='size'),
        ),
    ]
