# Generated by Django 3.0 on 2020-01-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments', verbose_name='file'),
        ),
    ]
