# Generated by Django 3.0 on 2020-02-16 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20200216_1436'),
        ('note', '0002_auto_20200213_1122'),
    ]

    operations = [
    ]
