# Generated by Django 3.0 on 2020-02-11 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_role'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='account.Role', verbose_name='role'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
