# Generated by Django 3.0 on 2020-02-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20191224_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('project', 'user__email'), 'verbose_name': 'membership', 'verbose_name_plural': 'memberships'},
        ),
    ]
