# Generated by Django 3.0 on 2020-02-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200211_1238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskstatus',
            unique_together={('project', 'name')},
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='slug',
        ),
    ]
